#+TITLE: アプリ設定
#+AUTHOR: Naoki Ueda
#+OPTIONS: \n:t H:1 toc:t author:nil email:nil timestamp:nil creator:nil num:t
#+LANGUAGE: ja
#+LaTeX_CLASS: normal
#+STARTUP: content
#+HTML_HEAD: <style type="text/css">body {font-family:"ricty";font-size:0.7em;}</style>
#+STYLE: <link rel="stylesheet" type="text/css" href="" />

* FilterList
** 日本語
*** 特徴
- シンプルを追求したリスト
- 「フィルター」機能で、自分なりにアイテムを抽出できる！
- どう使いこなすかは、お客様次第！
*** 基本的な使用方法
- ■アイテムモード
  - 通常のアイテムを追加していきます。
- ■タグモード
- ■フィルターモード
*** 追加予定の機能
- クラウドとの同期機能
- iPad, Mac との同期
** 英語
*** Features
- This application is very SIMPLE to use.
- You can customize with "Filter" feature!
- How use is depend on you!
*** Basic Usage
* COMMENT 参考
** Cal2todo
Cal2todoは予定を素早く確認・済チェックしていく予定実行サポートアプリです。
■こんな方におすすめ!
・カレンダーと別にtodoリストをわざわざ登録するのは面倒
・せっかく立てた予定が、割り込み作業などで後ろにズレることがある
・一日の予定をすべて終わらせてスッキリしたい!

■その日の残り予定をさっと確認でき、完了しなかった予定は自動繰越や延期機能で簡単に予定の組み直しができます。買い物リスト、ゴミだし予定、仕事のタスク、さまざまな用途でご活用ください。 iCloud / googleカレンダーを使えばPCからも入力できます。iPhoneカレンダーの予定がそのままチェックリストになるCal2todoをご活用ください。

■データをカレンダーに保存するので。。
・cal2todoで入力した予定が、他カレンダーアプリや同期したPCでもそのまま見れる！
　予定タイトルにもチェックマークをつける機能で完了した予定も一目瞭然！
・PCでさっと入力した予定をcal2todoでチェックできる！


■ビジネスカテゴリ一位獲得実績
多くのブログで評価いただいています。
「とうとう出会った！カレンダーの予定をチェックリストで表示できる最速快適カレンダーアプリ」〜frasm
「即ドック入り！カレンダーをチェックリスト化する「Cal2todo」が便利すぎて手放せなくなった！」〜Yu_notes.
「超便利!忙しい人にオススメのアプリですよ」〜アップス!!!
「ようやく自分にあったtodoアプリに出会えた感じ!」〜Apple Products Fan
「まるでマーク・フォースターが強調したような設計（マニャーナの法則）」〜Nikkei WomanOnline


■特徴---------

○素早い起動！
　標準カレンダーより速く予定を確認！

○スッキリ見やすい！
　一画面に一日分の予定をリスト表示。タブやスワイプで日付を切り替え！

○予定の見落としゼロ！
　チェックした項目は非表示になり、必要な予定だけが表示されます。もちろん再表示も可能。

○フィルターで表示カレンダーを一発切り替え
　「todo」「買い物」などカレンダーを状況にあわせて切り替えられます。

○「延期」機能充実
　「１時間後に」「夜に」「土曜に」など選ぶだけで予定を変更！
　「来週に予定をコピー」などもできます。

○クイックバーで素早く予定追加
　右横のクイックバーより、時刻を選んで素早く予定追加できます。

○予定の自動くりこし
　スターをつければ未完了の予定は自動で今日に繰り越し！

○残り時間表示
　次の予定までの残り時間を常に表示！　開始間近の予定、遅れた予定は黄・赤で表示！

○アラームアプリ連携
　大人気の「Due」や「カウントダウンカレンダー」に予定を登録！

○クラウド活用
　iCloud、googleカレンダー利用で、PCで入力した予定がそのままリストに！
　チェック・スター記録はiCloudで他iOSデバイスと同期！

○URLスキーム対応
　safariブックマークレットから今みているページを「後で読む」として予定に追加できます。

○連絡先対応
　新規予定追加時、連絡先（アドレス帳）よりメール・電話・住所などを予定に貼付けられます。


■基本的な使い方
「TODAY」の予定を確認、済んだものにはチェックをいれていきましょう。チェックした予定は自動的に非表示になります。背景色が赤のものは開始時刻が過ぎた予定、黄色のものは1時間以内の予定です。予定を終わらせてチェックするか、右側のボタンを押して「延期」しましょう。

■延期機能
選ぶだけで日時を変更
-「今日」その予定の日付を今日にします。他にも「次の日」「来週」「3日後」など設定できます。
-「朝」時刻を今日の9時 (時間は設定変更できます)にします。すでに9時を過ぎている場合は明日の9時にします。
-「昼」「夕」「夜」それぞれ設定された時刻にします。
-「1時間後」「3時間後」「5時間後」その予定の時刻を今から~時間後にします。「今(0時間後)」も設定可能。また、「その予定の開始時刻から~時間後」という設定もできます。
-曜日ボタン(「月」〜「日」)選択した曜日に予定を移動します。

■クイック予定追加バー
リスト右横にすばやく予定追加するためのボタンを配置しました。 ボタンは上から「終日」「今」「朝」「昼」「夜」の5つです。 タップすると時刻を選択するサブメニューが開きますのでそちらから予定を追加してください。 
ボタンを長押しすると、その時間帯までリストをスクロールさせます。 予定が多く画面に入りきらない方はご利用ください。 


【その他】
・画面上部の日付をタップすると8週間カレンダー（設定でカスタマイズ可能）が表示されます。
・予定の詳細を変更したい場合は、行の中央あたりをタップすれば予定編集できます。編集した予定はiPhoneカレンダーに反映されます。
・リスト画面でスワイプ(横スライド)することで、削除ボタンが現れ、予定の削除ができます。
・表示するカレンダーを選択することができます。
・下のタブを2回タップすれば、手動再読み込みできます。

【ご注意】 
 ・本アプリは直近予定の実行をサポートするツールです。扱う期間は今週〜8週間です。
 ・チェックオン・オフ情報は、標準カレンダーには書き込まれません。あくまで本アプリ内で管理します。
 ・チェックオン・オフは、標準カレンダーの各予定に振られた「ID番号」で予定を識別しています。
  このため、例えば他社が提供する天気予報カレンダーなど、予報が更新されるたびIDが変わるものはそのたびチェックが外れてしまいます。
・原則として本アプリ停止中に標準カレンダーから予定を追加・削除しても cal2todoアイコンのアプリバッジには即反映されません。但し「APPのバックグラウンド更新」を有効にすることでiPhoneの決めた間隔でバッジ更新が可能です。

＜バックグラウンド更新（Background Fetch）について＞
-iOS7の新機能バックグラウンド更新によりアプリを閉じていても一定時間おきに最新の予定を確認し、アプリケーションバッジなどに反映します。
-更新頻度はユーザー様の利用状況などにより、iPhoneが決定します。
-PCなどからカレンダーに予定を追加されてもiPhone自体がその予定を受信しなければ更新は発生しません。
なかなか予定が更新されない場合は、iPhone標準カレンダーアプリを起動してみてください。

＜TextExpanderについて＞
アドオンでTextExpanderをご利用になる場合、TextExpanderがリマインダーへの接続を必要としているためcal2todoがリマインダーの許可を求める場合があります。TextExpanderアドオンをご利用の場合は、許可をお願いします。

＜googleカレンダーとの同期速度について＞
お使いのiPhoneの設定により、他デバイスとの同期タイミングが変化します。
もし、設定方法がわからないという方はアプリ内よりお問い合わせください。（「プライバシー」設定もご注意ください）

＜URLスキームについて＞
本アプリのURLスキームは「cal2todo://」または「cal2todo1://」です。
またサファリから予定を追加する「あとで読むブックマークレット」などはヘルプに記載しております。
